#spring:
#  datasource:
#    drive-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:5432/salsa-bd
#    password: 1qa2ws3ed
#    username: postgres
#    pool-name: ManagerPool
#    min-pool-size: 1
#    max-pool-size: 3
#    max-lifetime: 1800000
#    validation-timeout: 250
#    allow-bean-definition-overriding: true
spring:
  data:
    mongodb:
      uri: mongodb://arthur:1qa2ws3ed@localhost:27017/service?authSource=admin
